version: '3.8'

services:
  # 后端API服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: exam-system-backend
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-here-change-in-production
      - JWT_SECRET_KEY=your-jwt-secret-key-here-change-in-production
    ports:
      - "5001:5001"
    volumes:
      - ./backend/src/database:/app/src/database
      - ./backend/uploads:/app/uploads
      - ./backend/certificates:/app/certificates
    networks:
      - exam-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5001/api/auth/profile || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # 前端Web服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: exam-system-frontend
    ports:
      - "80:80"
    networks:
      - exam-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  exam-network:
    driver: bridge

